"""
SWARAKSHA — Metadata Forensics Analyzer

Inspects image and video file metadata for common signs of AI generation:
- EXIF software tags (Stable Diffusion, ComfyUI, DALL-E, Midjourney, etc.)
- PNG tEXt/iTXt chunks containing generation parameters
- IPTC DigitalSourceType fields
- C2PA / Content Credentials markers
- Absence of real camera EXIF (no camera model, no lens, no GPS)
- Suspicious JPEG quantization tables
- Known AI watermark patterns in file headers

This module does NOT use a neural network. It is pure file/metadata analysis.
"""

import os
import struct
from PIL import Image
from PIL.ExifTags import TAGS
from typing import Optional


# ── Known AI software signatures ───────────────────────────────────────────

AI_SOFTWARE_KEYWORDS = [
    # Stable Diffusion ecosystem
    "stable diffusion", "automatic1111", "a1111", "comfyui", "comfy ui",
    "invoke ai", "invokeai", "diffusionbee", "easy diffusion",
    "fooocus", "forge", "sd.next", "vladmandic",
    # Midjourney
    "midjourney",
    # OpenAI
    "dall-e", "dall·e", "dalle", "chatgpt", "openai",
    # Adobe Firefly
    "adobe firefly", "firefly",
    # Google
    "imagen", "gemini",
    # Meta
    "meta ai",
    # Runway, Pika, etc.
    "runway", "pika", "kling", "sora",
    # Generic
    "ai generated", "ai-generated", "generated by ai",
    "deepfake", "face swap", "faceswap",
    "gan", "generative adversarial",
]

# PNG text chunk keys that Stable Diffusion and similar tools write
SD_PNG_KEYS = [
    "parameters", "prompt", "negative_prompt", "negative prompt",
    "steps", "sampler", "cfg scale", "cfg_scale", "seed",
    "model", "model hash", "model_hash", "vae", "clip skip",
    "lora", "controlnet", "adetailer", "hires fix", "hires. fix",
    "sd model", "sd checkpoint", "workflow", "comfyui",
]

# EXIF fields that real cameras always populate
CAMERA_EXIF_FIELDS = [
    "Make", "Model", "LensModel", "LensMake",
    "FocalLength", "FNumber", "ExposureTime",
    "ISOSpeedRatings", "Flash",
]


class MetadataAnalyzer:
    """Analyzes image/video metadata for AI-generation fingerprints."""

    def analyze_image_file(self, file_path: str) -> dict:
        """
        Run all metadata checks on an image file.

        Args:
            file_path: Path to the image file on disk.

        Returns:
            dict with keys:
              - flags: list of str  (individual findings)
              - ai_metadata_detected: bool
              - confidence: str  ("none", "low", "medium", "high")
              - summary: str
        """
        flags = []

        try:
            img = Image.open(file_path)
        except Exception as e:
            return self._result(flags, error=str(e))

        # 1. EXIF / software tag analysis
        flags.extend(self._check_exif(img))

        # 2. PNG text chunk analysis
        if file_path.lower().endswith(".png"):
            flags.extend(self._check_png_text_chunks(img))

        # 3. Missing camera EXIF (suspicious for photos claiming to be real)
        flags.extend(self._check_missing_camera_exif(img))

        # 4. Check raw file bytes for C2PA / binary markers
        flags.extend(self._check_binary_markers(file_path))

        return self._result(flags)

    def analyze_image_bytes(self, image_bytes: bytes, filename: str = "image.jpg") -> dict:
        """
        Run metadata checks on raw image bytes.
        Writes to a temporary file internally since some checks need a file path.
        """
        import tempfile
        suffix = os.path.splitext(filename)[1] or ".jpg"
        try:
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                tmp.write(image_bytes)
                tmp_path = tmp.name
            return self.analyze_image_file(tmp_path)
        finally:
            if 'tmp_path' in locals() and os.path.exists(tmp_path):
                os.remove(tmp_path)

    def analyze_video_file(self, file_path: str) -> dict:
        """
        Run metadata checks on a video file.
        Video metadata is sparser, but some generators embed tags in MP4 atoms.
        """
        flags = []
        flags.extend(self._check_binary_markers(file_path))
        flags.extend(self._check_video_metadata(file_path))
        return self._result(flags)

    # ── Internal checks ─────────────────────────────────────────────────────

    def _check_exif(self, img: Image.Image) -> list:
        """Check EXIF data for AI software signatures."""
        flags = []
        try:
            exif_data = img._getexif()
            if not exif_data:
                return flags

            for tag_id, value in exif_data.items():
                tag_name = TAGS.get(tag_id, str(tag_id))
                if not isinstance(value, str):
                    continue

                value_lower = value.lower()

                # Check Software, ImageDescription, UserComment, ProcessingSoftware
                if tag_name in ("Software", "ProcessingSoftware", "ImageDescription",
                                "UserComment", "Make", "Artist", "Copyright"):
                    for keyword in AI_SOFTWARE_KEYWORDS:
                        if keyword in value_lower:
                            flags.append(f"EXIF '{tag_name}' contains AI marker: '{value}' (matched: {keyword})")
                            break

        except Exception:
            pass
        return flags

    def _check_png_text_chunks(self, img: Image.Image) -> list:
        """Check PNG tEXt/iTXt chunks for Stable Diffusion parameters."""
        flags = []
        try:
            info = img.info or {}
            for key, value in info.items():
                key_lower = key.lower().strip()

                # Direct key match against known SD keys
                for sd_key in SD_PNG_KEYS:
                    if sd_key in key_lower:
                        # Truncate value for display
                        preview = str(value)[:120]
                        flags.append(f"PNG text chunk '{key}' matches AI generation parameter (preview: {preview})")
                        break

                # Also check values for AI keywords if it's a string
                if isinstance(value, str):
                    value_lower = value.lower()
                    for keyword in AI_SOFTWARE_KEYWORDS:
                        if keyword in value_lower:
                            preview = str(value)[:120]
                            flags.append(f"PNG text chunk '{key}' value contains AI marker: '{keyword}' (preview: {preview})")
                            break
        except Exception:
            pass
        return flags

    def _check_missing_camera_exif(self, img: Image.Image) -> list:
        """
        Flag images that have EXIF but are missing all camera-specific fields.
        Real photos almost always have Make, Model, FocalLength etc.
        AI images typically have zero camera fields.
        """
        flags = []
        try:
            exif_data = img._getexif()
            if not exif_data:
                # No EXIF at all — suspicious but common for web images
                flags.append("No EXIF metadata found (common in AI-generated images, but also screenshots/web images)")
                return flags

            # Build a set of present tag names
            present_tags = set()
            for tag_id in exif_data:
                tag_name = TAGS.get(tag_id, "")
                if tag_name:
                    present_tags.add(tag_name)

            # Count how many camera fields are present
            camera_fields_present = sum(1 for f in CAMERA_EXIF_FIELDS if f in present_tags)

            if camera_fields_present == 0 and len(exif_data) > 0:
                flags.append(
                    f"EXIF exists ({len(exif_data)} tags) but contains zero camera fields "
                    f"(no Make, Model, Lens, FocalLength etc.) — common in AI-generated images"
                )

        except Exception:
            pass
        return flags

    def _check_binary_markers(self, file_path: str) -> list:
        """
        Scan raw file bytes for known AI watermarks and C2PA content credentials.
        """
        flags = []
        try:
            with open(file_path, "rb") as f:
                # Read first 64KB for header analysis
                header = f.read(65536)

                # C2PA / Content Credentials (used by Adobe, Microsoft, etc.)
                if b"c2pa" in header or b"C2PA" in header:
                    flags.append("C2PA Content Credentials marker found (content provenance standard)")

                if b"contentauth" in header.lower() if isinstance(header, str) else b"contentauth" in header:
                    flags.append("ContentAuth marker found (Adobe Content Authenticity)")

                # IPTC DigitalSourceType
                if b"digitalSourceType" in header:
                    flags.append("IPTC DigitalSourceType field found (may indicate AI origin)")

                # AI tool signatures in raw bytes
                raw_lower = header.lower()
                for keyword in ["stable diffusion", "comfyui", "midjourney",
                                "dall-e", "openai", "firefly"]:
                    if keyword.encode() in raw_lower:
                        flags.append(f"Raw file bytes contain AI tool signature: '{keyword}'")

        except Exception:
            pass
        return flags

    def _check_video_metadata(self, file_path: str) -> list:
        """Check video container metadata atoms for AI markers."""
        flags = []
        try:
            with open(file_path, "rb") as f:
                # Read a larger chunk for video containers
                data = f.read(262144)  # 256KB
                data_lower = data.lower()

                # Check for AI tool names in video metadata atoms
                ai_video_tools = [
                    "runway", "pika", "kling", "sora", "stable video",
                    "gen-2", "gen-3", "animatediff", "deforum",
                    "synthesia", "heygen", "d-id",
                ]
                for tool in ai_video_tools:
                    if tool.encode() in data_lower:
                        flags.append(f"Video container metadata contains AI tool signature: '{tool}'")

                # Check for common AI generation metadata in MP4 comment atoms
                if b"\xa9cmt" in data or b"\xa9too" in data:
                    # These are MP4 comment and encoding tool atoms
                    for keyword in AI_SOFTWARE_KEYWORDS:
                        if keyword.encode() in data_lower:
                            flags.append(f"MP4 metadata atom contains AI marker: '{keyword}'")
                            break

        except Exception:
            pass
        return flags

    # ── Result builder ───────────────────────────────────────────────────────

    def _result(self, flags: list, error: str = None) -> dict:
        """Build a structured result dict from collected flags."""
        if error:
            return {
                "flags": [],
                "ai_metadata_detected": False,
                "confidence": "error",
                "summary": f"Metadata analysis failed: {error}",
            }

        # Classify confidence based on number and type of flags
        # Filter out the "no EXIF" flag for counting — it's weak evidence
        strong_flags = [f for f in flags if "No EXIF metadata" not in f and "zero camera fields" not in f]
        weak_flags = [f for f in flags if f not in strong_flags]

        if len(strong_flags) >= 2:
            confidence = "high"
        elif len(strong_flags) == 1:
            confidence = "medium"
        elif len(weak_flags) > 0:
            confidence = "low"
        else:
            confidence = "none"

        ai_detected = confidence in ("medium", "high")

        if not flags:
            summary = "No AI metadata markers detected."
        else:
            summary = f"{len(flags)} metadata finding(s): {'; '.join(flags[:3])}"
            if len(flags) > 3:
                summary += f" (+{len(flags) - 3} more)"

        return {
            "flags": flags,
            "ai_metadata_detected": ai_detected,
            "confidence": confidence,
            "summary": summary,
        }
